In [4]:
import numpy as np

In [5]:
my_list1=[1,2,3,4]

In [6]:
my_array1 = np.array(my_list1)

In [7]:
my_list1

[1, 2, 3, 4]

In [8]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2=[11,22,33,44]

In [10]:
my_list = [my_list1,my_list2]

In [11]:
my_list

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [12]:
my_array = np.array(my_list)

In [13]:
my_array

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
print("as you can see the array is a matrix")

as you can see the array is a matrix


In [15]:
my_array.shape

(2, 4)

In [16]:
print("So since it's multidimensional, I can ask numpy what shape it is by saying .shape method.And so it looks like it's a two by four, which makes sense.")

So since it's multidimensional, I can ask numpy what shape it is by saying .shape method.And so it looks like it's a two by four, which makes sense.


In [18]:
my_array.dtype

dtype('int64')

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
my_zeros_array = np.zeros(5)

In [22]:
my_zeros_array.shape

(5,)

In [23]:
my_zeros_array.dtype

dtype('float64')

In [24]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.empty(5)

array([3.5e-323, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.arange(0,10,dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [37]:
np.arange(0,10,1.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])