In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
arr1=np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [4]:
arr1

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [5]:
arr1*arr1

array([[   1,    4,    9,   16,   25],
       [ 100,  400,  900, 1600, 2500]])

In [6]:
arr1-arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
print("let's create an array that is a reciprocal of a fraction.")

let's create an array that is a reciprocal of a fraction.


In [8]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.1       , 0.05      , 0.03333333, 0.025     , 0.02      ]])

In [9]:
arr1**3

array([[     1,      8,     27,     64,    125],
       [  1000,   8000,  27000,  64000, 125000]])