In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#universal functions are basic functions you can apply to an array

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
#we can take the exponential of any value of an array

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([ 0.82998051,  0.47032618, -0.57021148,  0.72090308,  0.52157329,
       -2.29964015,  2.71266861, -0.67977534, -0.17954236,  0.14400831])

In [12]:
B = np.random.randn(10)

In [13]:
B

array([-1.60793113, -0.08625169,  0.7941432 , -0.70147044, -2.06858726,
        1.15644502, -0.58088307,  0.16965705, -1.99802392,  0.29881552])

In [14]:
#binary functions, addition among arrays
np.add(A,B)

array([-0.77795062,  0.38407449,  0.22393172,  0.01943263, -1.54701397,
       -1.14319513,  2.13178554, -0.51011829, -2.17756628,  0.44282383])

In [15]:
#find the maximum between the two arrays values
np.maximum(A,B)

array([ 0.82998051,  0.47032618,  0.7941432 ,  0.72090308,  0.52157329,
        1.15644502,  2.71266861,  0.16965705, -0.17954236,  0.29881552])

In [17]:
website = "https://docs.scipy.org/doc/numpy/reference/ufuncs.html"
import webbrowser
webbrowser.open(website) #you can check here all the math operations

True