In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr 

array([0, 1, 2, 3, 4])

In [4]:
np.save("my-array",arr)

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load("my-array.npy")

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load("my-array.npy")
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.savez("ziparray.npz",x=arr1,y=arr2)#save two arrays in a zip file

In [11]:
archive_array = np.load("ziparray.npz")

In [13]:
archive_array["x"]

array([0, 1, 2, 3, 4])

In [14]:
archive_array["y"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#save and load text files

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.savetxt("mytextarray.txt",arr,delimiter=',')

In [26]:
arr = np.loadtxt("mytextarray.txt", delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])